=encoding utf-8

=head1 NAME

bsvn

=head1 DESCRIPTION

=head2 初期設定

 $ cd /some/where/working_copy/
 $ bsvn --init http://svn.example.com/some/directory

--init の引数には、trunk などがあるディレクトリを指定する。

=head2 使い方

ブランチ branches/a1 に switch する。

 $ bsvn switch @branches/a1

作業中ブランチのリビジョン BASE を branches/work にコピーする。

 $ bsvn copy @.@BASE @branches/work

=head1 License and Copyright

Copyright (C) 2011 YAMAMOTO, N

This program is free software; you can redistribute it and/or modify it
under the terms of either: the GNU General Public License as published
by the Free Software Foundation; or the Artistic License.

See http://dev.perl.org/licenses/ for more information.
